In [2]:
import pandas as pd

data = pd.read_csv("Listers.csv")

In [4]:
data.head()

  user_id;date;cnt_adverts;age;cnt_contacts;revenue
0                        100;2022-01-01;6;21;119;53
1                        100;2022-01-02;2;21;200;18
2                        100;2022-01-03;6;21;193;42
3                        100;2022-01-04;2;21;143;38
4                        100;2022-01-05;2;21;190;40

In [3]:
import pandas as pd

data = pd.read_csv("Listers.csv", sep=";")

data.head()

   user_id        date  cnt_adverts   age  cnt_contacts  revenue
0    100.0  2022-01-01          6.0  21.0         119.0     53.0
1    100.0  2022-01-02          2.0  21.0         200.0     18.0
2    100.0  2022-01-03          6.0  21.0         193.0     42.0
3    100.0  2022-01-04          2.0  21.0         143.0     38.0
4    100.0  2022-01-05          2.0  21.0         190.0     40.0

In [4]:
data["revenue"] = data["revenue"].astype(float)

revenue_by_user = data.groupby("user_id")["revenue"].sum()

avg_revenue_per_user = revenue_by_user.mean()

print("Средний доход на пользователя:", round(avg_revenue_per_user, 2))

Средний доход на пользователя: 156.48

In [6]:
# Оставляем по одному возрасту на каждого пользователя
age_by_user = data.groupby("user_id")["age"].first()

# Считаем медиану возраста пользователей
median_age = age_by_user.median()

print("Медиана возраста пользователя:", median_age)

Медиана возраста пользователя: 28.0